export interface SummaryScores {
  environmental: number;
  social: number;
  governance: number;
  overall: number;
}

export interface EmissionsPoint {
  month: string;
  co2e: number;
}

export interface DepartmentRank {
  department: string;
  score: number;
}

export type ActivityType = "success" | "warning" | "info" | "document";

export interface ActivityItem {
  type: ActivityType;
  text: string;
  timestamp: string;
}

export interface NotificationItem {
  id: number;
  title: string;
  message: string;
  is_read: boolean;
  created_at: string;
  type: string;
}

export interface EmissionFactorItem {
  id: number;
  name: string;
  activity_type: string;
  unit: string;
  co2e_per_unit: number;
  source_reference: string;
  status: string;
}

export interface ProductProfileItem {
  id: number;
  product_name: string;
  sku: string;
  category: string;
  sustainability_score: number;
  status: string;
}

export interface PolicyItem {
  id: number;
  title: string;
  category: string;
  version: string;
  effective_date: string;
  status: string;
  requires_acknowledgement: boolean;
}

export interface AuditItem {
  id: number;
  title: string;
  department_name: string;
  audit_date: string;
  scope: string;
  status: string;
  overall_rating: number;
}

export interface ComplianceIssueItem {
  id: number;
  description: string;
  severity: string;
  status: string;
  due_date: string;
  owner_name: string;
}

export const summaryScores: SummaryScores = {
  environmental: 82,
  social: 74,
  governance: 88,
  overall: 81,
};

export const emissionsTrend: EmissionsPoint[] = [
  { month: "Jan", co2e: 1420 },
  { month: "Feb", co2e: 1385 },
  { month: "Mar", co2e: 1350 },
  { month: "Apr", co2e: 1390 },
  { month: "May", co2e: 1320 },
  { month: "Jun", co2e: 1280 },
  { month: "Jul", co2e: 1245 },
  { month: "Aug", co2e: 1265 },
  { month: "Sep", co2e: 1190 },
  { month: "Oct", co2e: 1155 },
  { month: "Nov", co2e: 1120 },
  { month: "Dec", co2e: 1085 },
];

export const departmentRanking: DepartmentRank[] = [
  { department: "Manufacturing", score: 88 },
  { department: "R&D", score: 81 },
  { department: "Corporate", score: 76 },
  { department: "Sales", score: 74 },
  { department: "Logistics", score: 69 },
];

export const recentActivity: ActivityItem[] = [
  {
    type: "success",
    text: "Priya completed 'Zero Waste Week'",
    timestamp: "12 min ago",
  },
  {
    type: "warning",
    text: "New compliance issue raised in Logistics",
    timestamp: "1 hr ago",
  },
  {
    type: "info",
    text: "42 new carbon transactions logged",
    timestamp: "3 hr ago",
  },
  {
    type: "document",
    text: "R&D team acknowledged the Anti-Corruption Policy",
    timestamp: "5 hr ago",
  },
  {
    type: "success",
    text: "Sales team reached their CSR participation target",
    timestamp: "Yesterday",
  },
  {
    type: "info",
    text: "Q3 ESG report generated by the Governance team",
    timestamp: "Yesterday",
  },
];

export const sampleNotifications: NotificationItem[] = [
  {
    id: 1,
    title: "Challenge approved",
    message: "Your green commute challenge was approved and XP was awarded.",
    is_read: false,
    created_at: new Date().toISOString(),
    type: "approval",
  },
  {
    id: 2,
    title: "New compliance issue",
    message: "A new governance issue needs owner assignment.",
    is_read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    type: "warning",
  },
];

export const sampleEmissionFactors: EmissionFactorItem[] = [
  { id: 1, name: "Grid Electricity", activity_type: "Purchase", unit: "kWh", co2e_per_unit: 0.45, source_reference: "EPA 2026", status: "Active" },
  { id: 2, name: "Diesel Fleet", activity_type: "Fleet", unit: "L", co2e_per_unit: 2.68, source_reference: "DEFRA 2026", status: "Active" },
  { id: 3, name: "Air Travel", activity_type: "Expense", unit: "km", co2e_per_unit: 0.19, source_reference: "ICAO 2026", status: "Draft" },
];

export const sampleProductProfiles: ProductProfileItem[] = [
  { id: 1, product_name: "Soteria Laptop Sleeve", sku: "ES-CASE-01", category: "Accessories", sustainability_score: 88, status: "Active" },
  { id: 2, product_name: "Carbon Smart Bottle", sku: "ES-BTL-02", category: "Merch", sustainability_score: 81, status: "Active" },
  { id: 3, product_name: "Renewable Desk Lamp", sku: "ES-LAMP-03", category: "Office", sustainability_score: 76, status: "Draft" },
];

export const samplePolicies: PolicyItem[] = [
  { id: 1, title: "Anti-Corruption Policy", category: "Governance", version: "1.0", effective_date: "2026-05-01", status: "Active", requires_acknowledgement: true },
  { id: 2, title: "Supplier Ethics Charter", category: "Governance", version: "1.2", effective_date: "2026-06-01", status: "Draft", requires_acknowledgement: false },
];

export const sampleAudits: AuditItem[] = [
  { id: 1, title: "Q2 Internal Audit", department_name: "Administration", audit_date: "2026-07-01", scope: "Process compliance review", status: "Open", overall_rating: 92 },
  { id: 2, title: "Vendor Compliance Review", department_name: "Procurement", audit_date: "2026-06-18", scope: "Supplier due diligence", status: "Resolved", overall_rating: 84 },
];

export const sampleComplianceIssues: ComplianceIssueItem[] = [
  { id: 1, description: "Missing owner assignment for vendor review", severity: "Medium", status: "Open", due_date: "2026-07-20", owner_name: "Riya Sharma" },
  { id: 2, description: "Late policy acknowledgement by sales team", severity: "Low", status: "In_Progress", due_date: "2026-07-18", owner_name: "Aarav Mehta" },
];
