export interface SummaryScores {
  environmental: number;
  social: number;
  governance: number;
  overall: number;
}

export interface EmissionsPoint {
  month: string;
  co2e: number;
}

export interface DepartmentRank {
  department: string;
  score: number;
}

export type ActivityType = "success" | "warning" | "info" | "document";

export interface ActivityItem {
  type: ActivityType;
  text: string;
  timestamp: string;
}

export const summaryScores: SummaryScores = {
  environmental: 82,
  social: 74,
  governance: 88,
  overall: 81,
};

export const emissionsTrend: EmissionsPoint[] = [
  { month: "Jan", co2e: 1420 },
  { month: "Feb", co2e: 1385 },
  { month: "Mar", co2e: 1350 },
  { month: "Apr", co2e: 1390 },
  { month: "May", co2e: 1320 },
  { month: "Jun", co2e: 1280 },
  { month: "Jul", co2e: 1245 },
  { month: "Aug", co2e: 1265 },
  { month: "Sep", co2e: 1190 },
  { month: "Oct", co2e: 1155 },
  { month: "Nov", co2e: 1120 },
  { month: "Dec", co2e: 1085 },
];

export const departmentRanking: DepartmentRank[] = [
  { department: "Manufacturing", score: 88 },
  { department: "R&D", score: 81 },
  { department: "Corporate", score: 76 },
  { department: "Sales", score: 74 },
  { department: "Logistics", score: 69 },
];

export const recentActivity: ActivityItem[] = [
  {
    type: "success",
    text: "Priya completed 'Zero Waste Week'",
    timestamp: "12 min ago",
  },
  {
    type: "warning",
    text: "New compliance issue raised in Logistics",
    timestamp: "1 hr ago",
  },
  {
    type: "info",
    text: "42 new carbon transactions logged",
    timestamp: "3 hr ago",
  },
  {
    type: "document",
    text: "R&D team acknowledged the Anti-Corruption Policy",
    timestamp: "5 hr ago",
  },
  {
    type: "success",
    text: "Sales team reached their CSR participation target",
    timestamp: "Yesterday",
  },
  {
    type: "info",
    text: "Q3 ESG report generated by the Governance team",
    timestamp: "Yesterday",
  },
];
